version: '3.7'
services:
  web:
    image: nginx:mainline-alpine
    ports:
      - 3000:3000
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
      - ./out:/usr/share/nginx/html
