apiVersion: apps/v1
kind: Deployment
metadata:
  name: corybuecker-com
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
          resources:
            requests:
              cpu: 5m
              memory: 5Mi
            limits:
              cpu: 10m
              memory: 10Mi
