on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v1

      - uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - uses: google-github-actions/setup-gcloud@v0

      - run: gcloud auth configure-docker us-central1-docker.pkg.dev -q

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/corybuecker:${{ github.sha }}
            us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/corybuecker:latest
          cache-from: type=registry,ref=us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/corybuecker:buildcache
          cache-to: type=registry,ref=us-central1-docker.pkg.dev/bueckered-272522/github-actions-repo/corybuecker:buildcache,mode=max
