name: Integration

on:
  push:
    branches:
      - main

env:
  CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
  CLOUDSDK_COMPUTE_REGION: us-central1
  CLOUDSDK_COMPUTE_ZONE: us-central1-c

jobs:
  image:
    name: Build image
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 297.0.1
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Setup Docker
        run: gcloud auth configure-docker

      - name: Checkout
        uses: actions/checkout@master

      - name: Build image
        run: docker build -t ${{ secrets.IMAGE_TAG }}:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ secrets.IMAGE_TAG }}:${{ github.sha }}
