name: Integration

on:
  push:
    branches:
      - main

env:
  CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
  CLOUDSDK_COMPUTE_REGION: us-central1
  CLOUDSDK_COMPUTE_ZONE: us-central1-c
  MIX_ENV: production
  NODE_ENV: production

jobs:
  image:
    name: Build image
    
    needs:
      - frontend
      - backend
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 297.0.1
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Setup Docker
        run: gcloud auth configure-docker

      - name: Checkout
        uses: actions/checkout@master

      - name: Build image
        run: docker build -t ${{ secrets.IMAGE_TAG }}:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ secrets.IMAGE_TAG }}:${{ github.sha }}

  frontend:
    name: Frontend checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 14
      
      - name: Checkout
        uses: actions/checkout@master

      - name: Download frontend dependencies
        run: npm install

      - name: Check outdated
        run: npm outdated

      # - name: Audit
      #   run: npm audit --production

      - name: Lint
        run: npx eslint '*/**/*.{js,ts,tsx,json}' --max-warnings 0

  backend:
    name: Backend checks

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev
    
    steps:
      - name: Setup Elixir
        uses: actions/setup-elixir@master
        with:
          otp-version: 22.2.1
          elixir-version: 1.10.3

      - name: Checkout
        uses: actions/checkout@master

      - name: Download and build backend dependencies
        run: mix deps.get && mix deps.compile

      - name: Check outdated
        run: mix hex.outdated

      - name: Lint
        run: mix credo --strict
