name: Build and deploy to Cloud Run

on:
  push:
    branches:
      - master

env:
  CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
  CLOUDSDK_RUN_PLATFORM: managed
  CLOUDSDK_RUN_REGION: us-central1
  MIX_ENV: prod
  NODE_ENV: production

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Elixir
        uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.2.1
          elixir-version: 1.9.4

      - name: Setup Node
        uses: actions/setup-node@v1.3.0
        with:
          node-version: 12.14.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 274.0.1
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Download frontend dependencies
        run: npm install

      - name: Download and build backend dependencies
        run: mix deps.get && mix deps.compile

      - name: Build backend
        run: mix run -e "Builder.build"

      - name: Build frontend
        run: npx webpack

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build image
        run: docker build -t ${{ secrets.IMAGE_TAG }}:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ secrets.IMAGE_TAG }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} --image ${{ secrets.IMAGE_TAG }}:${{ github.sha }} --service-account ${{ secrets.SERVICE_ACCOUNT }}
